# cloudbuild.yaml
steps:

# Clone your repository (replace with your actual repository URL)
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/Achugh007/an-app.git'] 

# Fetch the specific feature branch
- name: 'gcr.io/cloud-builders/git'
  args: ['fetch', 'origin', 'feature-new'] 

# Checkout the feature-new branch
- name: 'gcr.io/cloud-builders/git'
  args: ['checkout', 'feature-new']

# Terraform Init
- name: 'hashicorp/terraform:light'
  id: 'terraform-init'
  dir: 'terraform'  # Navigate to the terraform directory
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      terraform init \
        -backend-config="bucket=sks-terraform" \
        -backend-config="prefix=terraform/state/${BRANCH_NAME}"

# Terraform Plan
- name: 'hashicorp/terraform:light'
  id: 'terraform-plan'
  dir: 'terraform'  # Navigate to the terraform directory
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      terraform plan \
        -var="region=us-east1" \  # Specify the desired region
        -var="environment_name=${BRANCH_NAME#feature-}" \
        -out=tfplan

# Terraform Apply
- name: 'hashicorp/terraform:light'
  id: 'terraform-apply'
  dir: 'terraform'  # Navigate to the terraform directory
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      terraform apply -auto-approve tfplan
