steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - functions
  - deploy
  - serverless
  - '--runtime'
  - nodejs14
  - '--trigger-http'
  - '--entry-point'
  - quoteGenerator
  - '--source'
  - .
options:
  logging: CLOUD_LOGGING_ONLY
